version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.17.2
    container_name: elk_es
    environment:
      - TZ=Asia/Shanghai
      - node.name=es-node-1
      - cluster.name=elk-docker
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 降低到512MB
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk-net
    deploy:
      resources:
        limits:
          memory: 1G    # 降低到1GB
          cpus: '1.0'

  kibana:
    image: kibana:8.17.2
    container_name: elk_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - TZ=Asia/Shanghai
    ports:
      - "5601:5601"
    volumes:
      - kibana-data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - elk-net
    deploy:
      resources:
        limits:
          memory: 512m  # 降低到512MB
          cpus: '0.5'

  logstash:
    image: logstash:8.17.3
    container_name: elk_logstash
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m  # 降低到256MB
      - TZ=Asia/Shanghai
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - elk-net
    deploy:
      resources:
        limits:
          memory: 512m  # 降低到512MB
          cpus: '0.3'

volumes:
  es-data:
  kibana-data:

networks:
  elk-net:
    driver: bridge
